// Regenerates lib/abi.ts from Foundry build output. Run after `forge build`: npm run abi
import { readFileSync, writeFileSync } from "node:fs";

const names = ["FlipGuardGovernance", "MockRiskRegistry", "MockGovernanceToken"];
const body = names
  .map((n) => {
    const { abi } = JSON.parse(readFileSync(`contracts/out/${n}.sol/${n}.json`, "utf8"));
    return `export const ${n[0].toLowerCase() + n.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const;`;
  })
  .join("\n\n");
writeFileSync("lib/abi.ts", `// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit.\n\n${body}\n`);
console.log("lib/abi.ts written");
